name: Markdown Lint

on:
  pull_request:
    branches:
      - main # Or your default branch name

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli2

      - name: Run markdownlint
        # FIX: Changed exclusion patterns from '#' to '!'
        run: markdownlint-cli2 --config .markdownlint.jsonc "**/*.md" "!node_modules" "!.git"